### ISSUE TITLE
Trained HF model is not available

### ISSUE THREAD

**Issue by SLSravanthi** [audreycs/ImpScore#1]
The link for accessing trained HF models is giving 404 error. I want to use the trained model on my data for calculating the Impscore.

**Comment by audreycs** [comment]
Hello, the Hugging Face repository is still being built. We will publish the first version of ImpScore soon.

**Comment by audreycs** [comment]
Hello, ~~the trained model is available on Huggingface now. https://huggingface.co/audreyeleven/ImpScore~~

We have made the metric into a python package that everyone can download through `pip install implicit-score`. Please see the README.md for more details.
